### ISSUE TITLE
ggml-python server

### ISSUE THREAD

**Issue by yadamonk** [abetlen/ggml-python#1]
I just wanted to express my gratitude for your effort on this project. I'm a fan of [llama-cpp-python](https://github.com/abetlen/llama-cpp-python) and the prospect of also running mpt, replit, and starcoder models is incredibly exciting, especially given their permissive licensing.

**Comment by yadamonk** [comment]
I just realized that the focus of this repo is decidedly more low-level. Is it then correct to assume that the most efficient way to run [llama-cpp-python](https://github.com/abetlen/llama-cpp-python) with non-llama models, such as [mpt](https://github.com/ggerganov/ggml/tree/master/examples/mpt), [replit](https://github.com/ggerganov/ggml/tree/master/examples/replit), or [starcoder](https://github.com/ggerganov/ggml/tree/master/examples/starcoder), would simply involve setting the environment variable LLAMA_CPP_LIB to the corresponding binary, given that most arguments appear to align?

In that case it might already be possible to use starcoder with [gpt-code-ui](https://github.com/ricklamers/gpt-code-ui).

**Comment by abetlen** [comment]
Hey @yadamonk thank you so much!

To clarify a little, I have two goals for this project:

1. Expose the ggml.h interface to use directly from python. This is currently possible but as you've probably realised quite low-level.
2. Expose the ggml-based models in a way that makes them easy to install and use in the same way as the llama-cpp-python project.

The issue with the second goal is that those models do not yet have APIs in the same way that llama.cpp does. This leaves two options for implementing these, first is to adapt those c++ examples into unofficial APIs and bind to those or write python implementations using the low-level or one abstraction layer above. I'm going to try the second approach as it seems more flexible.

**Comment by yadamonk** [comment]
Hi @abetlen, thank you so much for clarifying. I agree that the second approach is the right way to go about things long term.

**Comment by yadamonk** [comment]
I'm super excited to see that you're working on an example for replit, especially given the recent code instruct version by [teknium](https://huggingface.co/teknium/Replit-v2-CodeInstruct-3B). I know it's still early days but do you have a rough estimate when it might be possible to connect the replit model to a web UI?

**Comment by abetlen** [comment]
@yadamonk tonight hopefully!

Also, I've tested it with Teknium's CodeInstruct v2 model and it works great, q4_0 should be able to run with ~2GB memory required.

**Comment by abetlen** [comment]
Quick preview of what I'm working on, this is using gpu weight offloading with approx 1.5GB of VRAM. With the fastapi server I was able to drop it into vscode (and vim) and get a local copilot working

https://github.com/abetlen/ggml-python/assets/6826477/bcf4be54-6f5a-49e3-963f-61c0b7c96d9e

**Comment by yadamonk** [comment]
Absolutely amazing! I hope I'll find some time to play with it today. Thanks again for all your work moving the ecosystem around ggml forward.
