### ISSUE TITLE
use `from __future__ import annotations` to avoid writing `"Context"`

### ISSUE THREAD

**Issue by wuyudi** [abetlen/ggml-python#2]
without
![image](https://github.com/abetlen/ggml-python/assets/30024051/4e5e74ab-0f70-4328-ab2a-24bfb378128b)

![image](https://github.com/abetlen/ggml-python/assets/30024051/6a99185b-6afb-40e1-9911-af4880301826)

```py
class A:
    a: "A"
```

with

![image](https://github.com/abetlen/ggml-python/assets/30024051/250e0547-0f26-4dae-b9b9-6ff28066b936)

```py
from __future__ import annotations
class A:
    a: A
```

I'd like to propose a PR to help improve this if you don't mind.

**Comment by abetlen** [comment]
Sure, sounds good!
